estimated_gas_cost_of_withdraw = "100000"
max_total_home_contract_balance = "10000000000000000000"
max_single_deposit_value = "1000000000000000000"

[home]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
ipc = "/Users/marek/Library/Application Support/io.parity.ethereum/jsonrpc.ipc"
required_confirmations = 0

[home.contract]
bin = "contracts/EthereumBridge.bin"

[foreign]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
ipc = "/Users/marek/Library/Application Support/io.parity.ethereum/jsonrpc.ipc"
required_confirmations = 0

[foreign.contract]
bin = "contracts/KovanBridge.bin"

[authorities]
accounts = [
	"0x006e27b6a72e1f34c626762f3c4761547aff1421",
]
required_signatures = 1

[transactions]
# these happen on `home`:
home_deploy = { gas = 1000000 , gas_price = 0 }
withdraw_relay = { gas = 200000 , gas_price = 0 }

# these happen on `foreign`:
foreign_deploy = { gas = 3000000 , gas_price = 0 }
deposit_relay = { gas = 150000 , gas_price = 0 }

withdraw_confirm = { gas = 300000 , gas_price = 0 }
